export const changelogs = {
    '1.0.0': ['Initial release.'],
    '1.0.1': ['Removed post decode data in nw command.', 'Changed stained glass to blank in inventory command.'],
    '1.0.2': ['Fixed nw command and now using my own api fork.'],
    '1.0.3': [
        'Fixed wrong color format on nw command for master stars.',
        'Fixed gemstone and rune show up weird unicode character in nw command.',
    ],
    '1.0.4': [
        'Added custom command.',
        'Fixed kicked for being able to use drop/hotbar key in inventory command.',
        'Fixed hotm calculation.',
        'Fixed some commands giving first profile instead last save because of bugged profile.',
    ],
    '1.0.5': [
        'Complete recode all features.',
        'Now using direct Hypixel API instead of third party so it gives much faster respond.',
        'Added blaze slayer.',
        'Changed Senither weight to LappySheep weight.',
        'Fixed unicode on nw command.',
        'Changed color on help command when the command is disabled/error while loading.',
    ],
    '1.0.6': [
        'Fixed apikey doesn\'t save properly.',
        'Fixed some typos.',
        'Fixed commands not registered properly when first install.',
    ],
    '1.0.7': ['Attempted to fix error and spamming log.'],
    '1.0.8': [
        'Added new pcheck command.',
        'Added personal vault and equipment to nw command.',
        'Added item count to nw command.',
        'Fixed spacing and typo on cata command.',
    ],
    '1.0.9': [
        'Fixed the module requiring requestV2 that causing the whole module doesn\'t work when you don\'t have requestV2 installed.',
    ],
    '1.1.0': ['Fixed placed crystal on sbhotm command.', 'Fixed MVP rank showed as VIP.'],
    '1.1.1': [
        'Added carpentry to player and sbskills command.',
        'Added crimson essence to essence command.',
        'Added equipment to inventory command.',
        'Made inventory command can be executed even when API inventory disabled.',
        'Added trophyfish command.',
    ],
    '1.1.2': [
        'Updated networth API and the calculation.',
        'Networth command now showing sacks.',
        'Networth command now showing enchanted book name.',
    ],
    '1.1.3': ['Fixed no last save profile.', 'Updated lily weight calculation.'],
    '1.1.4': ['Fixed sbprofiles command.'],
    '1.1.5': [
        'Fixed minor typo in nw command.',
        'Fixed addNotation not simplified decimal.',
        'Colorized sacks item in nw command.',
    ],
    '1.1.6': ['Added new category in nw command.', 'Backup Ashcon API using Mojang API to reduce rate limit.'],
    '1.1.7': [
        'Fixed pcheck not running when someone join from party finder.',
        'Added pcheck for kuudra party finder (will select automatically).',
        'Added some more items list in pcheck command.',
        'Added option to also scan backpack and enderchest for pcheck.',
    ],
    '1.1.8': [
        'Fixed pcheck error when no item id.',
        'Fixed error when no selected profile.',
        'Fixed error when Ashcon API return error other than 429.',
    ],
    '1.1.9': [
        'Added tab auto completion for commands.',
        'Added sb level to player command.',
        'Added crimson command.',
        'Code consistency part 1.',
    ],
    '1.3.0': ['Now using my own backend API so doesn\'t need any apikey.'],
    '1.3.1': ['Fixed color level to use new one in player command.'],
    '1.3.2': ['Added vampire slayer.', 'Fixed player command returning error for old player data.'],
    '1.3.3': ['Changed to temporary domain.'],
    '2.0.0': [
        'This updates reset your config.',
        'Moved API wrapper to my backend API.',
        'Now all command only need to request 1 API endpoint. This should make command responds much faster.',
        'Better chat handler, loading commands, and error messages.',
        'Optimized some commands.',
        'Removed sbecsetkey command.',
        'Added new changelogs chat notification.',
        'sbec command now dynamically load.',
        'Added Senither weight to weight command.',
        'Better perks display for cata command.',
        'Added new check command (for individual player check instead of party).',
        'Added show additional dungeon items and hide duplicate options for check and pcheck command.',
        'Added options to hide self check when joining party finder.',
        'Added profile age and game mode logo in sbprofiles command.',
        'Better ginfo command (Added many other informations).',
        'Changed how hotm level displayed and show disabled perks in sbhotm command.',
        'Fixed so many bug that I can\'t mention each.',
    ],
};
