export const nodeToName = {
    mining_speed_2: "Mining Speed II",
    powder_buff: "Powder Buff",
    mining_fortune_2: "Mining Fortune II",
    vein_seeker: "Vein Seeker",
    lonesome_miner: "Lonesome Miner",
    professional: "Professional",
    mole: "Mole",
    fortunate: "Fortunate",
    great_explorer: "Great Explorer",
    maniac_miner: "Maniac Miner",
    goblin_killer: "Goblin Killer",
    special_0: "Peak of the Mountain",
    star_powder: "Star Powder",
    daily_effect: "Sky Mall",
    mining_madness: "Mining Madness",
    mining_experience: "Seasoned Mineman",
    efficient_miner: "Efficient Miner",
    experience_orbs: "Orbiter",
    front_loaded: "Front Loaded",
    precision_mining: "Precision Mining",
    random_event: "Luck of the Cave",
    daily_powder: "Daily Powder",
    fallen_star_bonus: "Crystallized",
    mining_speed_boost: "Mining Speed Boost",
    titanium_insanium: "Titanium Insanium",
    mining_fortune: "Mining Fortune",
    forge_time: "Quick Forge",
    pickaxe_toss: "Pickobulus",
    mining_speed: "Mining Speed"
}